/**
 * PRICING — structured as categories → packages, matching Section 12–19
 * of the spec exactly. All prices are in INR (₹). Nothing here is
 * invented — this mirrors what Prince provided directly.
 */
const PRICING_CATEGORIES = [
  {
    id: "website-development",
    name: "Website Development",
    note: "",
    packages: [
      {
        name: "Starter",
        price: "₹8,999",
        period: "one-time",
        badge: "",
        blurb: "For small businesses that need a clean, professional site.",
        features: [
          "3–5 pages",
          "Responsive design",
          "Mobile optimization",
          "Contact form",
          "Basic SEO setup",
          "Social integration",
          "Google Maps",
          "Basic animations",
          "2 revision rounds",
          "Deployment assistance",
          "Basic performance optimization",
        ],
      },
      {
        name: "Professional",
        price: "₹14,999",
        period: "one-time",
        badge: "Most Popular",
        blurb: "Everything in Starter, plus a stronger design system and SEO setup.",
        features: [
          "5–8 pages",
          "Premium UI/UX",
          "Advanced animations",
          "Blog-ready architecture",
          "Advanced contact forms",
          "Google Analytics setup",
          "Advanced SEO setup",
          "Speed optimization",
          "Custom sections",
          "3 revision rounds",
          "Deployment support",
        ],
      },
      {
        name: "Premium",
        price: "₹24,999",
        period: "one-time",
        badge: "",
        blurb: "A full CMS-backed site for businesses that manage content often.",
        features: [
          "8–12+ pages",
          "Advanced UI/UX",
          "Advanced animations / 3D where appropriate",
          "CMS / Admin Panel",
          "Blog management",
          "Advanced forms",
          "Advanced SEO",
          "Performance optimization",
          "Security hardening",
          "Analytics setup",
          "5 revision rounds",
          "Post-launch support",
        ],
      },
    ],
  },
  {
    id: "seo",
    name: "SEO",
    note: "We never guarantee search rankings — no agency honestly can.",
    packages: [
      {
        name: "Starter",
        price: "₹5,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Technical SEO basics", "On-page SEO", "Keyword research", "Meta title/description optimization", "Basic monthly report"],
      },
      {
        name: "Growth",
        price: "₹9,999",
        period: "/month",
        badge: "Most Popular",
        blurb: "",
        features: [
          "Everything in Starter",
          "Local SEO",
          "Google Business Profile optimization",
          "Content recommendations",
          "Internal linking",
          "Competitor research",
          "Monthly performance report",
          "Ongoing optimization",
        ],
      },
      {
        name: "Premium",
        price: "₹14,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: [
          "Everything in Growth",
          "Advanced technical SEO",
          "Deeper competitor analysis",
          "Content strategy",
          "Advanced local SEO",
          "Conversion-focused optimization",
          "Detailed monthly reporting",
          "Continuous SEO improvements",
        ],
      },
    ],
  },
  {
    id: "local-seo",
    name: "Local SEO / Google Business Profile",
    note: "We never guarantee search rankings.",
    packages: [
      { name: "Starter", price: "₹3,999", period: "one-time", badge: "", blurb: "", features: [] },
      { name: "Growth", price: "₹6,999", period: "/month", badge: "", blurb: "", features: [] },
      { name: "Premium", price: "₹11,999", period: "/month", badge: "", blurb: "", features: [] },
    ],
  },
  {
    id: "social-media-management",
    name: "Social Media Management",
    note: "Paid ad spend, influencer fees, and professional photo/video production are billed separately unless explicitly included.",
    packages: [
      {
        name: "Starter",
        price: "₹6,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Up to 8 posts/month", "Basic content planning", "Captions", "Hashtag research", "Profile optimization", "Monthly report"],
      },
      {
        name: "Growth",
        price: "₹9,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Up to 12 posts/month", "Content calendar", "Captions", "Hashtag strategy", "Basic creative direction", "Engagement monitoring", "Monthly report"],
      },
      {
        name: "Premium",
        price: "₹14,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Up to 20 posts/month", "Advanced content strategy", "Content calendar", "Creative direction", "Engagement monitoring", "Performance analysis", "Monthly optimization report"],
      },
    ],
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing",
    note: "Client advertising spend (Meta/Google budget) is not included in any package.",
    packages: [
      {
        name: "Starter",
        price: "₹9,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Digital marketing strategy", "Basic audience research", "Campaign planning", "Basic SEO/social recommendations", "Monthly report"],
      },
      {
        name: "Growth",
        price: "₹14,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Strategy + campaign management", "Audience research", "Conversion-focused landing-page recommendations", "Social media strategy", "SEO coordination", "Analytics monitoring", "Monthly optimization"],
      },
      {
        name: "Premium",
        price: "₹19,999",
        period: "/month",
        badge: "",
        blurb: "",
        features: ["Full digital marketing strategy", "Multi-channel planning", "Advanced campaign management", "Conversion optimization", "Analytics and reporting", "Continuous optimization", "Monthly strategy review"],
      },
    ],
  },
  {
    id: "ai-automation",
    name: "AI Automation",
    note: "Advanced projects may require a custom quote.",
    packages: [
      {
        name: "Starter",
        price: "₹9,999",
        period: "one-time",
        badge: "",
        blurb: "",
        features: ["Basic workflow automation", "1 automation workflow", "Basic AI integration", "Documentation"],
      },
      {
        name: "Business",
        price: "₹19,999",
        period: "one-time",
        badge: "Most Popular",
        blurb: "",
        features: ["Multiple workflow automations", "AI integration", "Business process automation", "Testing", "Documentation", "Basic support"],
      },
      {
        name: "Advanced",
        price: "₹29,999+",
        period: "custom",
        badge: "",
        blurb: "",
        features: ["Complex automation", "Multiple integrations", "Advanced AI workflows", "Custom logic", "Testing and optimization", "Documentation", "Support"],
      },
    ],
  },
  {
    id: "website-maintenance",
    name: "Website Maintenance",
    note: "",
    packages: [
      { name: "Basic", price: "₹1,999", period: "/month", badge: "", blurb: "", features: ["Minor content updates", "Basic troubleshooting", "Security/update checks"] },
      { name: "Standard", price: "₹3,499", period: "/month", badge: "Most Popular", blurb: "", features: ["Regular content updates", "Maintenance", "Performance checks", "Security/update checks", "Basic technical support"] },
      { name: "Premium", price: "₹4,999", period: "/month", badge: "", blurb: "", features: ["Priority maintenance", "Regular updates", "Performance monitoring", "Security checks", "Content updates", "Technical support"] },
    ],
  },
  {
    id: "landing-page-development",
    name: "Landing Page Development",
    note: "",
    packages: [
      {
        name: "Starter",
        price: "₹4,999",
        period: "one-time",
        badge: "",
        blurb: "",
        features: ["1 landing page", "Responsive design", "CTA", "Contact form", "Basic SEO", "2 revisions"],
      },
      {
        name: "Professional",
        price: "₹6,999",
        period: "one-time",
        badge: "Most Popular",
        blurb: "",
        features: ["Premium UI/UX", "Advanced sections", "Animations", "Conversion-focused structure", "Contact/lead form", "Analytics-ready", "3 revisions"],
      },
      {
        name: "Premium",
        price: "₹9,999",
        period: "one-time",
        badge: "",
        blurb: "",
        features: ["Advanced landing page", "Advanced animations / 3D where appropriate", "Conversion-focused design", "Advanced form", "Tracking-ready architecture", "Performance optimization", "5 revisions"],
      },
    ],
  },
];

module.exports = PRICING_CATEGORIES;
